- name: Configurer et optimiser un serveur MongoDB serveur / Mongos / Mongo shell
  hosts: "{{ target|default('dbsrv') }}"
  #vars:

  tasks:
    - name: "Installer les prérequis (gnupg et curl)"
      ansible.builtin.apt:
        name:
          - gnupg
          - curl
          - locate
          - htop
          - iftop
        state: present
        update_cache: yes
      tags: mongodb

    - name: "MongoDB | Télécharger la clé GPG de MongoDB"
      ansible.builtin.get_url:
        url: https://www.mongodb.org/static/pgp/server-8.0.asc
        dest: /tmp/mongodb-server-8.0.asc
        mode: '0644'
      tags: mongodb

    - name: "MongoDB | Installer la clé GPG de MongoDB"
      ansible.builtin.shell: |
        gpg --dearmor < /tmp/mongodb-server-8.0.asc | sudo tee /usr/share/keyrings/mongodb-server-8.0.gpg > /dev/null
      args:
        creates: /usr/share/keyrings/mongodb-server-8.0.gpg
      tags: mongodb

    # =================================================================
    # 2. Installation de MongoDB
  
    # - name: "Remove binaires"
    #   apt:
    #     name: "mongodb-org*"
    #     state: absent
    #   tags: mongodb
    #   fail_when: false

    - name: "MongoDB | Ajouter le référentiel MongoDB"
      ansible.builtin.apt_repository:
        repo: "deb [ arch=amd64 signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg ] https://repo.mongodb.org/apt/ubuntu noble/mongodb-org/8.0 multiverse"
        state: present
        update_cache: yes
      tags: mongodb

    
    - name: "MongoDB | Installer MongoDB"
      ansible.builtin.apt:
        name:
          - mongodb-org
          - mongodb-org-database
          - mongodb-org-server
          - mongodb-org-mongos
          - mongodb-org-tools
        state: present
      tags: mongodb
      
    - name: "MongoDB | Démarrer et activer le service mongod"
      ansible.builtin.service:
        name: mongod
        state: started
        enabled: yes
      tags: service
      
    - name: "MongoDB | Vérifier l'état du service"
      ansible.builtin.command: systemctl status mongod
      register: mongod_status
      changed_when: false
      tags: service
      
    - name: "MongoDB | Afficher l'état du service"
      ansible.builtin.debug:
        var: mongod_status.stdout_lines
      tags: service
